
CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    CONSTRAINT film PRIMARY KEY (id),
    CONSTRAINT name UNIQUE (name)
    );

DELETE FROM FILMS;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;